framework:
    messenger:
        transports:
            mailer_send:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              options:
                exchange: { name: 'mailer.email' }
                queues:
                  mailer.email.send: ~

        routing:
            'App\Message\SendEmailMessage': mailer_send
